### ISSUE TITLE
Push ExcelDna.Registration v1.0.0 to NUGET

### ISSUE THREAD

**Issue by drobertson123** [Excel-DNA/Registration#27]
It looks like you have the new registration package done. Could you please push it to Nuget.

The current version on Nuget is 0.34.7. This is causing issues with the integration package when I call ExcelRegistration.GetExcelFunctions()

System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'ExcelDna.Integration, Version=0.34.6373.42344, Culture=neutral, PublicKeyToken=e33b67d3bb5581e4' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by govert** [comment]
@drobertson123 Sorry for the delay - it just slipped through the cracks.

The packages have been pushed now - please let me know if you have any more trouble.

**Comment by drobertson123** [comment]
Thanks for the help on that.
