### ISSUE TITLE
Recover and forward AsyncTaskUtil to ExcelAsyncUtil

### ISSUE THREAD

**Issue by govert** [Excel-DNA/Registration#40]
See this discussion: https://groups.google.com/g/exceldna/c/9VtfJ6SkhdU

I think it's worthwhile to try to keep compatibility of the public interface of ExcelDna.Registration, where easy and not interfering with our refactoring plans. It would be good if code using ExcelDna.Registration continued to work without changes, maybe with 'Obsolete' attributes added to indicate the change.

In particular, we might restore the class and public interface of `ExcelDna.Registration.Util.AsyncTaskUtil`, to forward all calls to the `ExcelDna.Integration.ExcelAsyncUtil` class, and have some `Obsolete` attributes to indicate to recommended update path.

**Comment by Sergey-Vlasov** [comment]
Maybe we should mark the whole ExcelDna.Registration package as Obsolete instead of marking individual methods once I complete the migration?

**Comment by govert** [comment]
> Maybe we should mark the whole ExcelDna.Registration package as Obsolete instead of marking individual methods once I complete the migration?

Yes, that sounds good.
